#!/bin/bash

session_manager=(sddm)
desktop=(
  xfce4
  gtk3-engines-xfce
  tango-icon-theme
  blackbird-gtk-theme
  blueman
  network-manager-gnome
)
tools=(
  bluealsa
  gthumb
  gparted
  meld
  mousepad
  thunar-volman
  volumeicon-alsa
  xarchiver
  xfce4-cpugraph-plugin
  xfce4-notifyd
  xfce4-screenshooter
  xfce4-taskmanager
  xfce4-terminal
)
office=(
  libreoffice-l10n-de
  libreoffice-writer
  libreoffice-calc
  libreoffice-impress
)

main() {
  if [ $(whoami) != "root" ]; then
    echo "Ohne Root-Rechte geht's nicht!"
    exit 1
  fi

  restore_baschrc
  change_password
  option_gui_installation
  cleanup
  sleep 4
  reboot
}

change_password() {
  while [ -z "$new_pw" ]; do
    new_pw=$( whiptail --passwordbox "Passwort wurde vorhin zurückgesetzt. 
    Hier kannst du einen neuen angeben:" 9 40 3>&1 1>&2 2>&3 )
  done
  echo -e "$SUDO_USER:$new_pw" | chpasswd
}

cleanup() {
  rm /etc/systemd/system/getty@tty1.service.d/autologin.conf
  rm base-config file-list gui-installer
}

install_packages() {
  attempts=1

  while true; do
    if [ "$attempts" -gt 1 ]; then
      echo "Fehler bei der Installation. Versuche zu reparieren:"
      apt update --fix-missing
      apt -y upgrade
      sleep 4
    fi

    apt -y install "$@"

    if [ $? -ne 0 -a "$attempts" -lt 3 ]; then
      ((attempts++))
    else
      break;
    fi
  done

  if [ "$attempts" -eq 3 ]; then
    echo "Alle Versuche sind fehlgeschlagen. Die Installation kann nicht mehr fortgesetzt werden."
    exit 1
  fi
}

option_gui_installation() {
  if ( whiptail --yesno "Möchtest du Xfce als grafische Oberfläche installieren?" 9 40 ); then
    sed -i "s/\[all\]/\[all\]\ndtoverlay=vc4-fkms-v3d\ngpu_mem=128/g" /boot/config.txt

    echo "Die Installation erfolgt jetzt:"

    install_packages "${session_manager[@]}"
    install_packages "--no-install-recommends" "${desktop[@]}"
    install_packages "${tools[@]}"
    install_packages "${office[@]}"

    xfconf-query -c xsettings -p /Net/ThemeName -s "Blackbird"
    echo '[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=VolumeIcon
Comment=Volume Icon for ALSA
Exec=volumeicon' > /etc/xdg/autostart/VolumeIcon.desktop
  fi
}

restore_baschrc() {
  if [ -f .bashrc.backup ]; then
    rm .bashrc
    mv .bashrc.backup .bashrc
    chown $SUDO_USER:$SUDO_USER .bashrc
  fi
}


main "$@"
