#!/bin/bash

if [ $(whoami) != "root" ]; then
  echo "Ohne Root-Rechte geht's nicht!"
  exit 1
fi

rm .bashrc
mv .bashrc.backup .bashrc
chown $SUDO_USER:$SUDO_USER .bashrc

while [ -z "$new_pw" ]; do
  new_pw=$( whiptail --passwordbox "Passwort wurde vorhin zurückgesetzt. Hier kannst du einen neuen angeben:" 9 40 3>&1 1>&2 2>&3 )
done
echo -e "$SUDO_USER:$new_pw" | chpasswd

if ( whiptail --yesno "Möchtest du Xfce als grafische Oberfläche installieren?" 9 40 ); then
  echo "Die Installation erfolgt jetzt:"

  apt-get -y install --no-install-recommends xserver-xorg xinit
  apt-get -y install sddm
  apt-get -y install --no-install-recommends xfce4 xfce4-terminal blackbird-gtk-theme
  apt-get -y install tango-icon-theme meld mousepad ristretto xfce4-screenshooter thunar-volman libreoffice-l10n-de
fi

rm /etc/systemd/system/getty@tty1.service.d/autologin.conf
rm base-config file-list gui_install &&
sleep 4 && reboot
