#!/bin/bash

if [ $(whoami) != "root" ]; then
  echo "Ohne Root-Rechte geht's nicht!"
  exit 1
fi

if ( whiptail --yesno "Möchtest du Xfce als grafische Oberfläche installieren?" 9 40 ); then
  echo "Die Installation erfolgt jetzt:"

  apt-get -y install --no-install-recommends xserver-xorg xinit
  apt install sddm
  apt-get -y install --no-install-recommends xfce4 xfce4-terminal blackbird-gtk-theme
  apt install tango-icon-theme meld mousepad ristretto xfce4-screenshooter thunar-volman libreoffice-l10n-de
fi

rm .bashrc
mv .bashrc.backup .bashrc
chown $SUDO_USER:$SUDO_USER .bashrc
rm /etc/systemd/system/getty@tty1.service.d/autologin.conf
rm base-config file-list gui_install &&
sleep 4 && reboot
